config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'testmode#index'
  get '/logout', to: 'testmode#logout'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads
  end
  get '/docs', to: 'doc#index'
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/category.rb
class Category < ActiveRecord::Base
  #Each user has Categories
  belongs_to :user
  #Each category has files (Uploads) attached to it
  has_many :uploads, dependent: :destroy
  has_many :converts, dependent: :destroy

  def level
    Role.levels[(Section.find_by_name name).level.downcase]
  end

  def pdf?
    Section.find_by_name(name).pdf
  end

end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :departments, dependent: :destroy
end

app/models/committee.rb
class Committee < ActiveRecord::Base
end

app/models/convert.rb
class Convert < ActiveRecord::Base
  belongs_to :category
  belongs_to :upload
  #This is for the downloads from CloudConvert
  has_attached_file :download
  #Don't validate file type, it will be PDF anyway.
  do_not_validate_attachment_file_type :download
end

app/models/create.rb
class Create < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :college
  has_many :users, dependent: :destroy
  has_many :department_sections, dependent: :destroy
  has_many :sections, through: :department_sections
end

app/models/home.rb
class Home < ActiveRecord::Base
	email = :email
	print email
end

app/models/recusal.rb
class Recusal < ActiveRecord::Base
  belongs_to :user
  belongs_to :candidate, class_name: 'User' 
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  enum level: [ :candidate, :department, :college, :provost, :tech ]
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :department_sections, dependent: :destroy

  def pdf?
    pdf ? "Yes" : "No"
  end
end

app/models/sign_in.rb
class SignIn < ActiveRecord::Base
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :category
  has_one :convert, dependent: :destroy
  has_attached_file :upload
  #Don't check the attachment type, it could be anything!
  do_not_validate_attachment_file_type :upload

  include Rails.application.routes.url_helpers
  #Adds simple attributes to the uploaded file
  def to_jq_upload
    {
      "name" => read_attribute(:upload_file_name),
      "size" => read_attribute(:upload_file_size),
      "url" => upload.url(:original),
      "delete_url" => category_upload_path(category_id,self),
      "delete_type" => "DELETE",
      "thumbnail_url" => ActionController::Base.helpers.image_url(Icon.for_filename upload_file_name) 
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :department
  has_one :college, through: :department
  belongs_to :role
  #Categories belong to each user.
  has_many :categories, dependent: :destroy
  has_many :recusals, dependent: :destroy
  has_attached_file :dossier
  do_not_validate_attachment_file_type :dossier
  enum phase: [ :candidate, :department, :college, :provost ]
  # A net ID may only be registered once
  validates :netid, presence: true, uniqueness: true

  def level
    role[:level]
  end

  def level= new_level
    update role: Role.find_by_level(new_level)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	validates_presence_of :Review_id
	validates_presence_of :Review_Candidate_Profile_id
	validates_presence_of :user_id
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  def create
    @college = College.new(college_params)

    if @college.save
      redirect_to @college, notice: 'College was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /colleges/1
  def update
    if @college.update(college_params)
      redirect_to @college, notice: 'College was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /colleges/1
  def destroy
    @college.destroy
    redirect_to colleges_url, notice: 'College was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def college_params
      params.require(:college).permit(:name)
    end
end

app/helpers/cal_helper.rb
module CalHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/doc_helper.rb
module DocHelper
end

app/helpers/fdisk_helper.rb
module FdiskHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/colleges/_form.html.erb
<%= form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colleges/_form.html.slim
.row
  .col-xs-4
    = bootstrap_form_for @college do |f|
      - if @college.errors.any?
        #error_explanation
          h2 = "#{pluralize @college.errors.count, "error"} prohibited this college from being saved:"
          ul
            - @college.errors.full_messages.each do |message|
              li = message
    
      = f.text_field :name
      = f.primary

app/views/colleges/edit.html.erb
<h1>Editing college</h1>

<%= render 'form' %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/edit.html.slim
h1 Editing college

== render 'form'

br

= link_to 'Back', colleges_path, class: 'btn btn-warning'
br

app/views/colleges/index.html.erb
<h1>Listing Colleges</h1>

<table>
  <thead>
    <tr>
      <h5>College</h5>
      <H5>Name</h5>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New College', new_college_path %></br>
<%= link_to 'Home Page', homes_path %>

app/views/colleges/index.html.slim
h1 Select College 

table class=["table table-striped"]
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @colleges.each do |college|
      tr
        td = link_to college.name, users_path(college: college.id)
        - if current_user.role.tech?
          td = link_to 'Edit', edit_college_path(college), class: 'badge alert-warning'
          td = link_to raw('<em class="fa fa-trash-o"></em> Destroy'), college, data: {:confirm => 'Are you sure?'},
        :method => :delete, class: 'badge alert-danger'
br

= link_to 'New College', new_college_path, class: 'btn btn-primary'
br

app/views/colleges/new.html.erb
<h1>New college</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/new.html.slim
h1 New college

== render 'form'
br
= link_to 'Cancel', colleges_path, class: 'btn btn-warning'

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.slim
p#notice = notice

p
  strong Name:
  = @college.name

= link_to 'Edit', edit_college_path(@college)
'|
= link_to 'Back', colleges_path