config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'testmode#index'
  get '/logout', to: 'testmode#logout'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads
  end
  get '/docs', to: 'doc#index'
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/category.rb
class Category < ActiveRecord::Base
  #Each user has Categories
  belongs_to :user
  #Each category has files (Uploads) attached to it
  has_many :uploads, dependent: :destroy
  has_many :converts, dependent: :destroy

  def level
    Role.levels[(Section.find_by_name name).level.downcase]
  end

  def pdf?
    Section.find_by_name(name).pdf
  end

end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :departments, dependent: :destroy
end

app/models/committee.rb
class Committee < ActiveRecord::Base
end

app/models/convert.rb
class Convert < ActiveRecord::Base
  belongs_to :category
  belongs_to :upload
  #This is for the downloads from CloudConvert
  has_attached_file :download
  #Don't validate file type, it will be PDF anyway.
  do_not_validate_attachment_file_type :download
end

app/models/create.rb
class Create < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :college
  has_many :users, dependent: :destroy
  has_many :department_sections, dependent: :destroy
  has_many :sections, through: :department_sections
end

app/models/home.rb
class Home < ActiveRecord::Base
	email = :email
	print email
end

app/models/recusal.rb
class Recusal < ActiveRecord::Base
  belongs_to :user
  belongs_to :candidate, class_name: 'User' 
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  enum level: [ :candidate, :department, :college, :provost, :tech ]
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :department_sections, dependent: :destroy

  def pdf?
    pdf ? "Yes" : "No"
  end
end

app/models/sign_in.rb
class SignIn < ActiveRecord::Base
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :category
  has_one :convert, dependent: :destroy
  has_attached_file :upload
  #Don't check the attachment type, it could be anything!
  do_not_validate_attachment_file_type :upload

  include Rails.application.routes.url_helpers
  #Adds simple attributes to the uploaded file
  def to_jq_upload
    {
      "name" => read_attribute(:upload_file_name),
      "size" => read_attribute(:upload_file_size),
      "url" => upload.url(:original),
      "delete_url" => category_upload_path(category_id,self),
      "delete_type" => "DELETE",
      "thumbnail_url" => ActionController::Base.helpers.image_url(Icon.for_filename upload_file_name) 
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :department
  has_one :college, through: :department
  belongs_to :role
  #Categories belong to each user.
  has_many :categories, dependent: :destroy
  has_many :recusals, dependent: :destroy
  has_attached_file :dossier
  do_not_validate_attachment_file_type :dossier
  enum phase: [ :candidate, :department, :college, :provost ]
  # A net ID may only be registered once
  validates :netid, presence: true, uniqueness: true

  def level
    role[:level]
  end

  def level= new_level
    update role: Role.find_by_level(new_level)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	validates_presence_of :Review_id
	validates_presence_of :Review_Candidate_Profile_id
	validates_presence_of :user_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_filter :check_context
  add_crumb 'Dossier', '/sections'
  # GET /categories
  def index
    #Categories each belong to a user
    @categories = @user.categories.select { |category| current_user.role[:level] == category.level } 
    @total = @categories.map{ |c| c.uploads.length}.reduce :+
  end

  # GET /categories/1
  def show
    add_crumb @category.name, category_path
  end

  # GET /categories/new
  def new
    add_crumb 'New Section', new_category_path
    @category = @user.categories.new
  end

  # GET /categories/1/edit
  def edit
    add_crumb @category.name, category_path
  end

  # POST /categories
  def create
    @category = @user.categories.new category_params

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    add_crumb @category.name, category_path
    if @category.update category_params
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def phase_complete
    @user.update phase: @user[:phase] + 1
    session[:context_user] = nil
    redirect_to root_path, notice: 'Thank you! The next phase of review may now begin.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      set_user
      @category = @user.categories.find params[:id]
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit :name, :user_id
    end

    def set_user
      @user = context_user
    end
 
end

app/helpers/cal_helper.rb
module CalHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doc_helper.rb
module DocHelper
end

app/helpers/fdisk_helper.rb
module FdiskHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/categories/_downloadjs.html.erb
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnail_url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnail_url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnail_url?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.delete_url) { %}
                <button class="badge alert-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } else { %}
                <button class="badge alert-danger cancel">
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_uploader.html.erb
 <%= form_for [@category, Upload.new], html: { multipart: true, id: "fileupload"  } do |f| %>
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  <div class="row fileupload-buttonbar col-md-9">
    <div class="span7">
      <!-- The fileinput-button span is used to style the file input field as button -->
      <%= f.file_field :upload, class: 'hide'  %>
      <button type="submit" class="btn btn-primary start hide" id="save_all">
    </div>
    <div class="span5">
      <!-- The global progress bar -->
      <div class="progress progress-success progress-striped active fade">
        <div class="bar" style="width:0%;"></div>
      </div>
    </div>
  </div>
  <!-- The loading indicator is shown during image processing -->
  <div class="fileupload-loading"></div>
  <!-- The table listing the files available for upload/download -->
  <div class="row">
    <div class="col-md-4">
      <div class="well well-success" id="green_button"><h4><i class="fa fa-folder"></i> Click to add files...</h4></div>
    </div>
    <div class="col-md-1 text-center">
      <h4>OR</h4>
    </div>
    <div class="col-md-4">
      <div class="well"><h4><i class="fa fa-file"></i> Drag and drop files.</h4></div>
    </div>
    <div class="row">
      <div class="col-md-1 col-md-offset-9">
        <button class="btn btn-primary" id="blue_button"><i class="fa fa-upload"></i> Save All</button>
     </div>
   </div>
  </div>
  <table class="table table-bordered table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
  </table>
<% end %>
<script>
$('#green_button').bind("click" , function () {
  $('#upload_upload').click();
});

$('#blue_button').bind("click" , function (e) {
  e.preventDefault();
  $('#save_all').click();
});


var fileUploadErrors = {
maxFileSize: 'File is too big',
minFileSize: 'File is too small',
acceptFileTypes: 'Filetype not allowed',
maxNumberOfFiles: 'Max number of files exceeded',
uploadedBytes: 'Uploaded bytes exceed file size',
emptyResult: 'Empty file upload result'
};
</script>
<%= render 'uploadjs' %>
<%= render 'downloadjs' %>

<script type="text/javascript" charset="utf-8">
$(function () {
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload();
    //
    // Load existing files:
    $.getJSON($('#fileupload').prop('action'), function (files) {
      var fu = $('#fileupload').data('blueimpFileupload'),
      template;
      // This is broken for some reason
      //fu._adjustMaxNumberOfFiles(-files.length);
      console.log(files);
      template = fu._renderDownload(files)
        .appendTo($('#fileupload .files'));
      // Force reflow:
      fu._reflow = fu._transition && template.length &&
        template[0].offsetWidth;
      template.addClass('in');
      $('#loading').remove();
    });

});
</script>

app/views/categories/_uploadjs.html.erb
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="badge alert-primary start" disabled>
                    <i class="fa fa-upload"></i>
                    <span>Save</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="badge alert-danger cancel">
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}</script>

app/views/categories/convert.html.erb
<!-- This shows when conversions are complete -->
<h1 class="text-center text-success">    <%= @counter %> file(s) converted</h1>
<h2 class="text-center"><%= link_to 'Continue', converts_path, :class => "text-primary" %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Dossier Sections for <%= @user.name %></h2>
Click on each section name below to add files to that dossier section.
When you are ready to see your dossier, click "Preview Dossier" below.
If you are satisfied with your dossier, click "Submit Final Dossier" to send
your dossier to the department level for review.
<table class="table table-striped table-hover warning">
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category, class: 'display: block;' %></td>
      <td><span class="badge"><%= category.uploads.length %></span></td>
    </tr>
  <% end %>
    <tr>
      <td><strong>Total:</strong></td>
      <td><span class="badge"><%= @total %></span></td>
    </tr>
  </tbody>
</table>
<p>If you exit the application, saved items remain in your dossier.</p>
<div class="row">
  <div class="col-md-4"> 
  <%= link_to 'Preview Dossier', compile_path, class: 'btn btn-primary' %>
  </div>

  <div class="col-md-4 col-md-offset-2">
    <%= link_to "Submit Final Dossier to  #{User.phases.key context_user[:phase] + 1}", submit_path, class: 'btn btn-success', data: { confirm: 'By selecting, Yes, I acknowledge that my dossier is complete and ready for review. Any additional changes must be made through an administrator.' } %> 
  </div>
</div>
<script>
$(function () { $.fn.twitter_bootstrap_confirmbox.defaults = {
    fade: false,
    title: "Submit Final Dossier", // if title equals null window.top.location.origin is used
    cancel: "No",
    cancel_class: "btn cancel",
    proceed: "Yes",
    proceed_class: "btn proceed btn-primary"
} });
</script>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Section:</strong>
  <%= @category.name %>
</h2>

<%= render 'uploader' %>
<%= link_to 'Back to Dossier Sections', categories_path, class: "btn btn-warning" %>